CREATE TABLE IF NOT EXISTS positions_staffs
(
    id BIGSERIAL PRIMARY KEY,
    position_id BIGSERIAL NOT NULL,
    staff_id BIGSERIAL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_position_id FOREIGN KEY (position_id) REFERENCES positions(id),
    CONSTRAINT fk_staff_id FOREIGN KEY (staff_id) REFERENCES staffs(id)
);
